### ISSUE TITLE
requireCordovaModule no longer supported

### ISSUE THREAD

**Issue by basisesports** [ComethruApp/app#198]
When I get to a certain point in the build, it initially threw an error saying I couldn't use requireCordovaModule because it was no longer supported and I needed to replace it with require. However, when I do that, I get a new error:

```
req is not a function
TypeError: req is not a function
    at module.exports (/Users/user/comethru/app/plugins/cordova-plugin-app-preferences/bin/after_prepare.js:5:7)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:32)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:136:12)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:108:40
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[ERROR] An error occurred while running subprocess cordova.
```

This is the code in the after_prepare.js with the change to requireCordovaModule still in place:

```
module.exports = function (context) {
    var req = context.require,
        Q = req('q'),
        path = req('path'),
        ET = req('elementtree'),
        cordova = req('cordova'),
        cordova_lib = cordova.cordova_lib,
        cordova_lib_util = req('cordova-lib/src/cordova/util'),
        fs = require("./lib/filesystem")(Q, req('fs'), path),
        settings = require("./lib/settings")(fs, path),
        platforms = {};

    platforms.android = require("./lib/android")(context);
    platforms.ios = require("./lib/ios")(Q, fs, path, req('plist'), req('xcode'));
    // platforms.browser = require("./lib/browser")(Q, fs, path, req('plist'), req('xcode'));

```

**Comment by ErikBoesen** [comment]
I'm confused why you're using `req` instead of `require`.

**Comment by basisesports** [comment]
So despite initializing ```var req = context.require```, all other ```req``` references need to be updated to ```require```?

**Comment by ErikBoesen** [comment]
Give that a shot.

**Comment by basisesports** [comment]
So doing that gets me further along but then outputs the following error:
```
Cannot find module 'cordova'
Require stack:
- /Users/user/comethru/app/plugins/cordova-plugin-app-preferences/bin/after_prepare.js
- /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js
- /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js
- /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/plugman.js
- /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/cordova-lib.js
- /usr/local/lib/node_modules/cordova/src/help.js
- /usr/local/lib/node_modules/cordova/src/cli.js
- /usr/local/lib/node_modules/cordova/bin/cordova
Error: Cannot find module 'cordova'
Require stack:
- /Users/user/comethru/app/plugins/cordova-plugin-app-preferences/bin/after_prepare.js
- /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js
- /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js
- /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/plugman.js
- /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/cordova-lib.js
- /usr/local/lib/node_modules/cordova/src/help.js
- /usr/local/lib/node_modules/cordova/src/cli.js
- /usr/local/lib/node_modules/cordova/bin/cordova
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at module.exports (/Users/user/comethru/app/plugins/cordova-plugin-app-preferences/bin/after_prepare.js:8:13)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:32)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:136:12)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:108:40
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
I've run ```sudo npm uninstall -g cordova``` and ```install cordova@latest``` to no avail.

**Comment by ErikBoesen** [comment]
Installing `cordova@latest` is likely not a good move, I had to build with Cordova 8 because 9 was incompatible with this project for some reason (I don't remember why). How are you attempting to build?

**Comment by basisesports** [comment]
```ionic cordova build ios --prod --verbose``` is what I've been doing within the main app directory

**Comment by basisesports** [comment]
Do I need to install cordova@8.1.2 in the app directory?

**Comment by ErikBoesen** [comment]
Yes, that's a good idea. Not sure if it'll resolve this issue, but it'll help.

**Comment by basisesports** [comment]
Yeah, still not solving. Going to do some more digging.

**Comment by ErikBoesen** [comment]
Have been unable to reproduce; this is probably an issue with cordova versioning or something to that effect.
